UPCIEDEV PCI Express Universal driver: pciedev_ufn.h File Reference
pciedev_ufn.h File Reference
#include <linux/version.h>
#include <linux/pci.h>
#include <linux/types.h>
#include <linux/cdev.h>
#include <linux/interrupt.h>
#include <linux/fs.h>
#include <linux/proc_fs.h>
Data Structures
struct upciedev_file_list
struct pciedev_brd_info
struct pciedev_prj_info
struct pciedev_dev
struct pciedev_cdev
Defines
#define ASCII_BOARD_MAGIC_NUM 0x424F5244 /*BORD*/
#define ASCII_PROJ_MAGIC_NUM 0x50524F4A /*PROJ*/
#define ASCII_BOARD_MAGIC_NUM_L 0x626F7264 /*bord*/
#define WORD_BOARD_MAGIC_NUM 0x00
#define WORD_BOARD_ID 0x04
#define WORD_BOARD_VERSION 0x08
#define WORD_BOARD_DATE 0x0C
#define WORD_BOARD_HW_VERSION 0x10
#define WORD_BOARD_RESET 0x14
#define WORD_BOARD_TO_PROJ 0x18
#define WORD_PROJ_MAGIC_NUM 0x00
#define WORD_PROJ_ID 0x04
#define WORD_PROJ_VERSION 0x08
#define WORD_PROJ_DATE 0x0C
#define WORD_PROJ_RESERVED 0x10
#define WORD_PROJ_RESET 0x14
#define WORD_PROJ_NEXT 0x18
#define WORD_PROJ_IRQ_ENABLE 0x00
#define WORD_PROJ_IRQ_MASK 0x04
#define WORD_PROJ_IRQ_FLAGS 0x08
#define WORD_PROJ_IRQ_CLR_FLAGSE 0x0C
#define PCIED_FPOS 7
Typedefs
typedef struct upciedev_file_list upciedev_file_list
typedef struct pciedev_brd_info pciedev_brd_info
typedef struct pciedev_prj_info pciedev_prj_info
typedef struct pciedev_dev pciedev_dev
typedef struct pciedev_cdev pciedev_cdev
Functions
void upciedev_cleanup_module_exp (pciedev_cdev **)
int upciedev_init_module_exp (pciedev_cdev **, struct file_operations *, char *)
int pciedev_probe_exp (struct pci_dev *, const struct pci_device_id *, struct file_operations *, pciedev_cdev *, char *, int *)
int pciedev_remove_exp (struct pci_dev *dev, pciedev_cdev *, char *, int *)
int pciedev_open_exp (struct inode *, struct file *)
int pciedev_release_exp (struct inode *, struct file *)
ssize_t pciedev_read_exp (struct file *, char __user *, size_t, loff_t *)
ssize_t pciedev_write_exp (struct file *, const char __user *, size_t, loff_t *)
loff_t pciedev_llseek (struct file *, loff_t, int)
long pciedev_ioctl_exp (struct file *, unsigned int *, unsigned long *, pciedev_cdev *)
int pciedev_set_drvdata (struct pciedev_dev *, void *)
void * pciedev_get_drvdata (struct pciedev_dev *)
int pciedev_get_brdnum (struct pci_dev *)
pciedev_dev * pciedev_get_pciedata (struct pci_dev *)
void * pciedev_get_baddress (int, struct pciedev_dev *)
int pciedev_get_prjinfo (struct pciedev_dev *)
int pciedev_fill_prj_info (struct pciedev_dev *, void *)
int pciedev_get_brdinfo (struct pciedev_dev *)
int pciedev_check_scratch (struct pciedev_dev *, int)
int pciedev_setup_interrupt (irqreturn_t(*pciedev_interrupt)(int, void *, struct pt_regs *), struct pciedev_dev *, char *)
void register_upciedev_proc (int num, char *dfn, struct pciedev_dev *p_upcie_dev, struct pciedev_cdev *p_upcie_cdev)
void unregister_upciedev_proc (int num, char *dfn)
ssize_t pciedev_procinfo (struct file *filp, char *buf, size_t count, loff_t *offp)
Define Documentation
#define ASCII_BOARD_MAGIC_NUM 0x424F5244 /*BORD*/
Referenced by pciedev_get_brdinfo().
#define ASCII_BOARD_MAGIC_NUM_L 0x626F7264 /*bord*/
Referenced by pciedev_get_brdinfo().
#define ASCII_PROJ_MAGIC_NUM 0x50524F4A /*PROJ*/
Referenced by pciedev_fill_prj_info().
#define PCIED_FPOS 7
Referenced by pciedev_llseek(), pciedev_open_exp(), pciedev_read_exp(), and pciedev_write_exp().
#define WORD_BOARD_DATE 0x0C
Referenced by pciedev_get_brdinfo().
#define WORD_BOARD_HW_VERSION 0x10
Referenced by pciedev_get_brdinfo().
#define WORD_BOARD_ID 0x04
Referenced by pciedev_get_brdinfo().
#define WORD_BOARD_MAGIC_NUM 0x00
#define WORD_BOARD_RESET 0x14
#define WORD_BOARD_TO_PROJ 0x18
Referenced by pciedev_get_brdinfo().
#define WORD_BOARD_VERSION 0x08
Referenced by pciedev_get_brdinfo().
#define WORD_PROJ_DATE 0x0C
Referenced by pciedev_fill_prj_info().
#define WORD_PROJ_ID 0x04
Referenced by pciedev_fill_prj_info().
#define WORD_PROJ_IRQ_CLR_FLAGSE 0x0C
#define WORD_PROJ_IRQ_ENABLE 0x00
#define WORD_PROJ_IRQ_FLAGS 0x08
#define WORD_PROJ_IRQ_MASK 0x04
#define WORD_PROJ_MAGIC_NUM 0x00
#define WORD_PROJ_NEXT 0x18
Referenced by pciedev_fill_prj_info().
#define WORD_PROJ_RESERVED 0x10
Referenced by pciedev_fill_prj_info().
#define WORD_PROJ_RESET 0x14
#define WORD_PROJ_VERSION 0x08
Referenced by pciedev_fill_prj_info().
Typedef Documentation
typedef struct pciedev_brd_info pciedev_brd_info
typedef struct pciedev_cdev pciedev_cdev
typedef struct pciedev_dev pciedev_dev
typedef struct pciedev_prj_info pciedev_prj_info
typedef struct upciedev_file_list upciedev_file_list
Function Documentation
int pciedev_check_scratch (struct pciedev_dev * , int)
References pciedev_dev::dev_mut, pciedev_dev::mem_base0_end, pciedev_dev::mem_base1_end, pciedev_dev::mem_base2_end, pciedev_dev::mem_base3_end, pciedev_dev::mem_base4_end, pciedev_dev::mem_base5_end, pciedev_dev::memmory_base0, pciedev_dev::memmory_base1, pciedev_dev::memmory_base2, pciedev_dev::memmory_base3, pciedev_dev::memmory_base4, pciedev_dev::memmory_base5, RW_D16, RW_D32, RW_D8, pciedev_dev::scratch_bar, and pciedev_dev::scratch_offset.
Referenced by pciedev_read_exp().
int pciedev_fill_prj_info (struct pciedev_dev * , void *)
References ASCII_PROJ_MAGIC_NUM, pciedev_dev::brd_info_list, pciedev_prj_info::PCIEDEV_PROJ_DATE, pciedev_prj_info::PCIEDEV_PROJ_ID, pciedev_brd_info::PCIEDEV_PROJ_NEXT, pciedev_prj_info::PCIEDEV_PROJ_NEXT, pciedev_prj_info::PCIEDEV_PROJ_RESERVED, pciedev_prj_info::PCIEDEV_PROJ_VERSION, pciedev_dev::prj_info_list, pciedev_prj_info::prj_list, pciedev_dev::startup_prj_num, WORD_PROJ_DATE, WORD_PROJ_ID, WORD_PROJ_NEXT, WORD_PROJ_RESERVED, and WORD_PROJ_VERSION.
Referenced by pciedev_get_prjinfo().
void* pciedev_get_baddress (int , struct pciedev_dev *)
References pciedev_dev::memmory_base0.
int pciedev_get_brdinfo (struct pciedev_dev *)
References ASCII_BOARD_MAGIC_NUM, ASCII_BOARD_MAGIC_NUM_L, pciedev_dev::brd_info_list, pciedev_dev::memmory_base0, pciedev_brd_info::PCIEDEV_BOARD_DATE, pciedev_brd_info::PCIEDEV_BOARD_ID, pciedev_brd_info::PCIEDEV_BOARD_VERSION, pciedev_brd_info::PCIEDEV_HW_VERSION, pciedev_brd_info::PCIEDEV_PROJ_NEXT, pciedev_dev::startup_brd, WORD_BOARD_DATE, WORD_BOARD_HW_VERSION, WORD_BOARD_ID, WORD_BOARD_TO_PROJ, and WORD_BOARD_VERSION.
Referenced by pciedev_probe_exp().
int pciedev_get_brdnum (struct pci_dev *)
References pciedev_dev::brd_num.
void* pciedev_get_drvdata (struct pciedev_dev *)
References pciedev_dev::dev_str.
pciedev_dev* pciedev_get_pciedata (struct pci_dev *)
int pciedev_get_prjinfo (struct pciedev_dev *)
References pciedev_dev::brd_info_list, pciedev_dev::memmory_base0, pciedev_dev::memmory_base1, pciedev_dev::memmory_base2, pciedev_dev::memmory_base3, pciedev_dev::memmory_base4, pciedev_dev::memmory_base5, pciedev_fill_prj_info(), pciedev_brd_info::PCIEDEV_PROJ_NEXT, and pciedev_dev::startup_prj_num.
Referenced by pciedev_probe_exp().
long pciedev_ioctl_exp (struct file * , unsigned int * , unsigned long * , pciedev_cdev *)
References pciedev_dev::brd_info_list, device_ioctrl_data::cmd, device_ioctrl_data::data, pciedev_dev::dev_minor, pciedev_dev::dev_mut, pciedev_dev::dev_num, pciedev_dev::dev_sts, device_ioctrl_data::offset, pciedev_brd_info::PCIEDEV_BOARD_VERSION, PCIEDEV_DRIVER_VERSION, pciedev_cdev::PCIEDEV_DRV_VER_MAJ, pciedev_cdev::PCIEDEV_DRV_VER_MIN, PCIEDEV_FIRMWARE_VERSION, PCIEDEV_GET_STATUS, pciedev_dev::pciedev_pci_dev, PCIEDEV_PHYSICAL_SLOT, PCIEDEV_SCRATCH_REG, device_ioctrl_data::reserved, pciedev_dev::scratch_bar, pciedev_dev::scratch_offset, and pciedev_dev::slot_num.
loff_t pciedev_llseek (struct file * , loff_t , int)
References pciedev_dev::dev_minor, pciedev_dev::dev_num, pciedev_dev::dev_sts, and PCIED_FPOS.
Referenced by upciedev_init_module_exp().
int pciedev_open_exp (struct inode * , struct file *)
References pciedev_dev::cdev, pciedev_dev::dev_file_list, pciedev_dev::dev_file_ref, pciedev_dev::dev_minor, pciedev_dev::dev_mut, upciedev_file_list::file_cnt, upciedev_file_list::filp, upciedev_file_list::node_file_list, and PCIED_FPOS.
int pciedev_probe_exp (struct pci_dev * , const struct pci_device_id * , struct file_operations * , pciedev_cdev * , char * , int *)
References pciedev_dev::binded, pciedev_dev::bus_func, pciedev_dev::busNumber, pciedev_dev::class_code, pciedev_dev::dev_dma_64mask, pciedev_dev::dev_minor, pciedev_dev::dev_name, pciedev_dev::dev_sts, pciedev_dev::device_id, pciedev_dev::devNumber, pciedev_dev::funcNumber, pciedev_dev::irq_flag, pciedev_dev::irq_line, pciedev_dev::irq_mode, pciedev_dev::irq_pin, pciedev_dev::mem_base0, pciedev_dev::mem_base0_end, pciedev_dev::mem_base0_flag, pciedev_dev::mem_base1, pciedev_dev::mem_base1_end, pciedev_dev::mem_base1_flag, pciedev_dev::mem_base2, pciedev_dev::mem_base2_end, pciedev_dev::mem_base2_flag, pciedev_dev::mem_base3, pciedev_dev::mem_base3_end, pciedev_dev::mem_base3_flag, pciedev_dev::mem_base4, pciedev_dev::mem_base4_end, pciedev_dev::mem_base4_flag, pciedev_dev::mem_base5, pciedev_dev::mem_base5_end, pciedev_dev::mem_base5_flag, pciedev_dev::memmory_base0, pciedev_dev::memmory_base1, pciedev_dev::memmory_base2, pciedev_dev::memmory_base3, pciedev_dev::memmory_base4, pciedev_dev::memmory_base5, pciedev_dev::pci_dev_irq, pciedev_dev::pciedev_all_mems, pciedev_cdev::pciedev_class, pciedev_cdev::pciedev_dev_m, pciedev_get_brdinfo(), pciedev_get_prjinfo(), pciedev_cdev::PCIEDEV_MAJOR, pciedev_cdev::PCIEDEV_MINOR, pciedev_dev::pciedev_pci_dev, pciedev_cdev::pciedevModuleNum, register_upciedev_proc(), pciedev_dev::revision, pciedev_dev::rw_off0, pciedev_dev::rw_off1, pciedev_dev::rw_off2, pciedev_dev::rw_off3, pciedev_dev::rw_off4, pciedev_dev::rw_off5, pciedev_dev::scratch_bar, pciedev_dev::scratch_offset, pciedev_dev::slot_num, pciedev_dev::subdevice_id, pciedev_dev::subvendor_id, and pciedev_dev::vendor_id.
ssize_t pciedev_procinfo (struct file * filp, char * buf, size_t count, loff_t * offp)
References pciedev_dev::brd_info_list, pciedev_dev::brd_num, pciedev_dev::parent_dev, pciedev_brd_info::PCIEDEV_BOARD_DATE, pciedev_brd_info::PCIEDEV_BOARD_ID, pciedev_brd_info::PCIEDEV_BOARD_RESERVED, pciedev_brd_info::PCIEDEV_BOARD_VERSION, pciedev_cdev::PCIEDEV_DRV_VER_MAJ, pciedev_cdev::PCIEDEV_DRV_VER_MIN, pciedev_brd_info::PCIEDEV_HW_VERSION, pciedev_prj_info::PCIEDEV_PROJ_DATE, pciedev_prj_info::PCIEDEV_PROJ_ID, pciedev_brd_info::PCIEDEV_PROJ_NEXT, pciedev_prj_info::PCIEDEV_PROJ_NEXT, pciedev_prj_info::PCIEDEV_PROJ_RESERVED, pciedev_prj_info::PCIEDEV_PROJ_VERSION, pciedev_dev::prj_info_list, pciedev_prj_info::prj_list, pciedev_dev::slot_num, pciedev_dev::startup_prj_num, pciedev_cdev::UPCIEDEV_VER_MAJ, and pciedev_cdev::UPCIEDEV_VER_MIN.
ssize_t pciedev_read_exp (struct file * , char __user * , size_t , loff_t *)
References device_rw::barx_rw, device_rw::data_rw, pciedev_dev::dev_minor, pciedev_dev::dev_mut, pciedev_dev::dev_num, pciedev_dev::dev_sts, pciedev_dev::mem_base0_end, pciedev_dev::mem_base1_end, pciedev_dev::mem_base2_end, pciedev_dev::mem_base3_end, pciedev_dev::mem_base4_end, pciedev_dev::mem_base5_end, pciedev_dev::memmory_base0, pciedev_dev::memmory_base1, pciedev_dev::memmory_base2, pciedev_dev::memmory_base3, pciedev_dev::memmory_base4, pciedev_dev::memmory_base5, device_rw::mode_rw, device_rw::offset_rw, pciedev_dev::parent_dev, PCIED_FPOS, pciedev_dev::pciedev_all_mems, pciedev_check_scratch(), pciedev_cdev::PCIEDEV_DRV_VER_MAJ, pciedev_cdev::PCIEDEV_DRV_VER_MIN, pciedev_dev::pciedev_pci_dev, device_rw::rsrvd_rw, RW_D16, RW_D32, RW_D8, RW_INFO, device_rw::size_rw, and pciedev_dev::slot_num.
int pciedev_release_exp (struct inode * , struct file *)
References pciedev_dev::dev_file_list, pciedev_dev::dev_file_ref, pciedev_dev::dev_mut, upciedev_file_list::filp, and upciedev_file_list::node_file_list.
int pciedev_remove_exp (struct pci_dev * dev, pciedev_cdev * , char * , int *)
References pciedev_dev::binded, pciedev_dev::brd_num, pciedev_dev::dev_file_list, pciedev_dev::dev_file_ref, pciedev_dev::dev_mut, pciedev_dev::dev_num, pciedev_dev::dev_sts, upciedev_file_list::filp, pciedev_dev::irq_mode, pciedev_dev::mem_base0, pciedev_dev::mem_base0_end, pciedev_dev::mem_base0_flag, pciedev_dev::mem_base1, pciedev_dev::mem_base1_end, pciedev_dev::mem_base1_flag, pciedev_dev::mem_base2, pciedev_dev::mem_base2_end, pciedev_dev::mem_base2_flag, pciedev_dev::mem_base3, pciedev_dev::mem_base3_end, pciedev_dev::mem_base3_flag, pciedev_dev::mem_base4, pciedev_dev::mem_base4_end, pciedev_dev::mem_base4_flag, pciedev_dev::mem_base5, pciedev_dev::mem_base5_end, pciedev_dev::mem_base5_flag, pciedev_dev::memmory_base0, pciedev_dev::memmory_base1, pciedev_dev::memmory_base2, pciedev_dev::memmory_base3, pciedev_dev::memmory_base4, pciedev_dev::memmory_base5, upciedev_file_list::node_file_list, pciedev_dev::pci_dev_irq, pciedev_cdev::pciedev_class, pciedev_cdev::pciedev_dev_m, pciedev_cdev::PCIEDEV_MAJOR, pciedev_cdev::PCIEDEV_MINOR, pciedev_dev::pciedev_pci_dev, pciedev_cdev::pciedevModuleNum, pciedev_dev::prj_info_list, pciedev_prj_info::prj_list, pciedev_dev::rw_off0, pciedev_dev::rw_off1, pciedev_dev::rw_off2, pciedev_dev::rw_off3, pciedev_dev::rw_off4, pciedev_dev::rw_off5, pciedev_dev::slot_num, and unregister_upciedev_proc().
int pciedev_set_drvdata (struct pciedev_dev * , void *)
References pciedev_dev::dev_str.
int pciedev_setup_interrupt (irqreturn_t(*)(int, void *, struct pt_regs *) pciedev_interrupt, struct pciedev_dev * , char *)
References pciedev_dev::irq_flag, pciedev_dev::irq_mode, and pciedev_dev::pci_dev_irq.
ssize_t pciedev_write_exp (struct file * , const char __user * , size_t , loff_t *)
References device_rw::barx_rw, device_rw::data_rw, pciedev_dev::dev_minor, pciedev_dev::dev_mut, pciedev_dev::dev_num, pciedev_dev::dev_sts, DMA_DATA_OFFSET_BYTE, pciedev_dev::mem_base0_end, pciedev_dev::mem_base1_end, pciedev_dev::mem_base2_end, pciedev_dev::mem_base3_end, pciedev_dev::mem_base4_end, pciedev_dev::mem_base5_end, pciedev_dev::memmory_base0, pciedev_dev::memmory_base1, pciedev_dev::memmory_base2, pciedev_dev::memmory_base3, pciedev_dev::memmory_base4, pciedev_dev::memmory_base5, device_rw::mode_rw, device_rw::offset_rw, PCIED_FPOS, device_rw::rsrvd_rw, RW_D16, RW_D32, RW_D8, and device_rw::size_rw.
void register_upciedev_proc (int num, char * dfn, struct pciedev_dev * p_upcie_dev, struct pciedev_cdev * p_upcie_cdev)
References pciedev_cdev::pciedev_procdir.
Referenced by pciedev_probe_exp().
void unregister_upciedev_proc (int num, char * dfn)
Referenced by pciedev_remove_exp().
void upciedev_cleanup_module_exp (pciedev_cdev **)
References pciedev_cdev::pciedev_class, pciedev_cdev::pciedev_dev_m, pciedev_cdev::PCIEDEV_MAJOR, and pciedev_cdev::PCIEDEV_MINOR.
int upciedev_init_module_exp (pciedev_cdev ** , struct file_operations * , char *)
References pciedev_dev::binded, pciedev_dev::brd_num, pciedev_dev::cdev, pciedev_dev::dev_dma_64mask, pciedev_dev::dev_file_list, pciedev_dev::dev_file_ref, pciedev_dev::dev_minor, pciedev_dev::dev_mut, pciedev_dev::dev_num, pciedev_dev::dev_sts, upciedev_file_list::file_cnt, pciedev_dev::irq_mode, upciedev_file_list::node_file_list, pciedev_dev::null_dev, pciedev_dev::parent_dev, pciedev_dev::pciedev_all_mems, pciedev_cdev::pciedev_class, pciedev_cdev::pciedev_dev_m, pciedev_cdev::PCIEDEV_DRV_VER_MAJ, pciedev_cdev::PCIEDEV_DRV_VER_MIN, pciedev_llseek(), pciedev_cdev::PCIEDEV_MAJOR, pciedev_cdev::PCIEDEV_MINOR, pciedev_cdev::pciedevModuleNum, pciedev_dev::prj_info_list, pciedev_prj_info::prj_list, pciedev_cdev::UPCIEDEV_VER_MAJ, and pciedev_cdev::UPCIEDEV_VER_MIN.