UPCIEDEV PCI Express Universal driver: pciedev_ufn.c File Reference
pciedev_ufn.c File Reference
#include <linux/module.h>
#include <linux/fs.h>
#include <linux/sched.h>
#include <linux/proc_fs.h>
#include "pciedev_ufn.h"
Functions
int upciedev_init_module_exp (pciedev_cdev **pciedev_cdev_pp, struct file_operations *pciedev_fops, char *dev_name)
EXPORT_SYMBOL (upciedev_init_module_exp)
void upciedev_cleanup_module_exp (pciedev_cdev **pciedev_cdev_p)
EXPORT_SYMBOL (upciedev_cleanup_module_exp)
int pciedev_open_exp (struct inode *inode, struct file *filp)
EXPORT_SYMBOL (pciedev_open_exp)
int pciedev_release_exp (struct inode *inode, struct file *filp)
EXPORT_SYMBOL (pciedev_release_exp)
int pciedev_set_drvdata (struct pciedev_dev *dev, void *data)
EXPORT_SYMBOL (pciedev_set_drvdata)
void * pciedev_get_drvdata (struct pciedev_dev *dev)
EXPORT_SYMBOL (pciedev_get_drvdata)
int pciedev_get_brdnum (struct pci_dev *dev)
EXPORT_SYMBOL (pciedev_get_brdnum)
pciedev_dev * pciedev_get_pciedata (struct pci_dev *dev)
EXPORT_SYMBOL (pciedev_get_pciedata)
void * pciedev_get_baddress (int br_num, struct pciedev_dev *dev)
EXPORT_SYMBOL (pciedev_get_baddress)
int pciedev_setup_interrupt (irqreturn_t(*pciedev_interrupt)(int, void *, struct pt_regs *), struct pciedev_dev *pdev, char *dev_name)
EXPORT_SYMBOL (pciedev_setup_interrupt)
int pciedev_get_brdinfo (struct pciedev_dev *bdev)
EXPORT_SYMBOL (pciedev_get_brdinfo)
int pciedev_fill_prj_info (struct pciedev_dev *bdev, void *baddress)
EXPORT_SYMBOL (pciedev_fill_prj_info)
int pciedev_get_prjinfo (struct pciedev_dev *bdev)
EXPORT_SYMBOL (pciedev_get_prjinfo)
void register_upciedev_proc (int num, char *dfn, struct pciedev_dev *p_upcie_dev, struct pciedev_cdev *p_upcie_cdev)
void unregister_upciedev_proc (int num, char *dfn)
ssize_t pciedev_procinfo (struct file *filp, char *buf, size_t count, loff_t *offp)
EXPORT_SYMBOL (pciedev_procinfo)
Function Documentation
EXPORT_SYMBOL (upciedev_init_module_exp)
EXPORT_SYMBOL (upciedev_cleanup_module_exp)
EXPORT_SYMBOL (pciedev_open_exp)
EXPORT_SYMBOL (pciedev_release_exp)
EXPORT_SYMBOL (pciedev_set_drvdata)
EXPORT_SYMBOL (pciedev_get_drvdata)
EXPORT_SYMBOL (pciedev_get_brdnum)
EXPORT_SYMBOL (pciedev_get_pciedata)
EXPORT_SYMBOL (pciedev_get_baddress)
EXPORT_SYMBOL (pciedev_setup_interrupt)
EXPORT_SYMBOL (pciedev_get_brdinfo)
EXPORT_SYMBOL (pciedev_fill_prj_info)
EXPORT_SYMBOL (pciedev_get_prjinfo)
EXPORT_SYMBOL (pciedev_procinfo)
int pciedev_fill_prj_info (struct pciedev_dev * bdev, void * baddress)
References ASCII_PROJ_MAGIC_NUM, pciedev_dev::brd_info_list, pciedev_prj_info::PCIEDEV_PROJ_DATE, pciedev_prj_info::PCIEDEV_PROJ_ID, pciedev_brd_info::PCIEDEV_PROJ_NEXT, pciedev_prj_info::PCIEDEV_PROJ_NEXT, pciedev_prj_info::PCIEDEV_PROJ_RESERVED, pciedev_prj_info::PCIEDEV_PROJ_VERSION, pciedev_dev::prj_info_list, pciedev_prj_info::prj_list, pciedev_dev::startup_prj_num, WORD_PROJ_DATE, WORD_PROJ_ID, WORD_PROJ_NEXT, WORD_PROJ_RESERVED, and WORD_PROJ_VERSION.
Referenced by pciedev_get_prjinfo().
void* pciedev_get_baddress (int br_num, struct pciedev_dev * dev)
References pciedev_dev::memmory_base0.
int pciedev_get_brdinfo (struct pciedev_dev * bdev)
References ASCII_BOARD_MAGIC_NUM, ASCII_BOARD_MAGIC_NUM_L, pciedev_dev::brd_info_list, pciedev_dev::memmory_base0, pciedev_brd_info::PCIEDEV_BOARD_DATE, pciedev_brd_info::PCIEDEV_BOARD_ID, pciedev_brd_info::PCIEDEV_BOARD_VERSION, pciedev_brd_info::PCIEDEV_HW_VERSION, pciedev_brd_info::PCIEDEV_PROJ_NEXT, pciedev_dev::startup_brd, WORD_BOARD_DATE, WORD_BOARD_HW_VERSION, WORD_BOARD_ID, WORD_BOARD_TO_PROJ, and WORD_BOARD_VERSION.
Referenced by pciedev_probe_exp().
int pciedev_get_brdnum (struct pci_dev * dev)
References pciedev_dev::brd_num.
void* pciedev_get_drvdata (struct pciedev_dev * dev)
References pciedev_dev::dev_str.
pciedev_dev* pciedev_get_pciedata (struct pci_dev * dev)
int pciedev_get_prjinfo (struct pciedev_dev * bdev)
References pciedev_dev::brd_info_list, pciedev_dev::memmory_base0, pciedev_dev::memmory_base1, pciedev_dev::memmory_base2, pciedev_dev::memmory_base3, pciedev_dev::memmory_base4, pciedev_dev::memmory_base5, pciedev_fill_prj_info(), pciedev_brd_info::PCIEDEV_PROJ_NEXT, and pciedev_dev::startup_prj_num.
Referenced by pciedev_probe_exp().
int pciedev_open_exp (struct inode * inode, struct file * filp)
References pciedev_dev::cdev, pciedev_dev::dev_file_list, pciedev_dev::dev_file_ref, pciedev_dev::dev_minor, pciedev_dev::dev_mut, upciedev_file_list::file_cnt, upciedev_file_list::filp, upciedev_file_list::node_file_list, and PCIED_FPOS.
ssize_t pciedev_procinfo (struct file * filp, char * buf, size_t count, loff_t * offp)
References pciedev_dev::brd_info_list, pciedev_dev::brd_num, pciedev_dev::parent_dev, pciedev_brd_info::PCIEDEV_BOARD_DATE, pciedev_brd_info::PCIEDEV_BOARD_ID, pciedev_brd_info::PCIEDEV_BOARD_RESERVED, pciedev_brd_info::PCIEDEV_BOARD_VERSION, pciedev_cdev::PCIEDEV_DRV_VER_MAJ, pciedev_cdev::PCIEDEV_DRV_VER_MIN, pciedev_brd_info::PCIEDEV_HW_VERSION, pciedev_prj_info::PCIEDEV_PROJ_DATE, pciedev_prj_info::PCIEDEV_PROJ_ID, pciedev_brd_info::PCIEDEV_PROJ_NEXT, pciedev_prj_info::PCIEDEV_PROJ_NEXT, pciedev_prj_info::PCIEDEV_PROJ_RESERVED, pciedev_prj_info::PCIEDEV_PROJ_VERSION, pciedev_dev::prj_info_list, pciedev_prj_info::prj_list, pciedev_dev::slot_num, pciedev_dev::startup_prj_num, pciedev_cdev::UPCIEDEV_VER_MAJ, and pciedev_cdev::UPCIEDEV_VER_MIN.
int pciedev_release_exp (struct inode * inode, struct file * filp)
References pciedev_dev::dev_file_list, pciedev_dev::dev_file_ref, pciedev_dev::dev_mut, upciedev_file_list::filp, and upciedev_file_list::node_file_list.
int pciedev_set_drvdata (struct pciedev_dev * dev, void * data)
References pciedev_dev::dev_str.
int pciedev_setup_interrupt (irqreturn_t(*)(int, void *, struct pt_regs *) pciedev_interrupt, struct pciedev_dev * pdev, char * dev_name)
References pciedev_dev::irq_flag, pciedev_dev::irq_mode, and pciedev_dev::pci_dev_irq.
void register_upciedev_proc (int num, char * dfn, struct pciedev_dev * p_upcie_dev, struct pciedev_cdev * p_upcie_cdev)
References pciedev_cdev::pciedev_procdir.
Referenced by pciedev_probe_exp().
void unregister_upciedev_proc (int num, char * dfn)
Referenced by pciedev_remove_exp().
void upciedev_cleanup_module_exp (pciedev_cdev ** pciedev_cdev_p)
References pciedev_cdev::pciedev_class, pciedev_cdev::pciedev_dev_m, pciedev_cdev::PCIEDEV_MAJOR, and pciedev_cdev::PCIEDEV_MINOR.
int upciedev_init_module_exp (pciedev_cdev ** pciedev_cdev_pp, struct file_operations * pciedev_fops, char * dev_name)
References pciedev_dev::binded, pciedev_dev::brd_num, pciedev_dev::cdev, pciedev_dev::dev_dma_64mask, pciedev_dev::dev_file_list, pciedev_dev::dev_file_ref, pciedev_dev::dev_minor, pciedev_dev::dev_mut, pciedev_dev::dev_num, pciedev_dev::dev_sts, upciedev_file_list::file_cnt, pciedev_dev::irq_mode, upciedev_file_list::node_file_list, pciedev_dev::null_dev, pciedev_dev::parent_dev, pciedev_dev::pciedev_all_mems, pciedev_cdev::pciedev_class, pciedev_cdev::pciedev_dev_m, pciedev_cdev::PCIEDEV_DRV_VER_MAJ, pciedev_cdev::PCIEDEV_DRV_VER_MIN, pciedev_llseek(), pciedev_cdev::PCIEDEV_MAJOR, pciedev_cdev::PCIEDEV_MINOR, pciedev_cdev::pciedevModuleNum, pciedev_dev::prj_info_list, pciedev_prj_info::prj_list, pciedev_cdev::UPCIEDEV_VER_MAJ, and pciedev_cdev::UPCIEDEV_VER_MIN.