UPCIEDEV PCI Express Universal driver: pciedev_rw_exp.c File Reference
pciedev_rw_exp.c File Reference
#include <linux/module.h>
#include <linux/fs.h>
#include <asm/uaccess.h>
#include "pciedev_ufn.h"
#include "pciedev_io.h"
Functions
ssize_t pciedev_read_exp (struct file *filp, char __user *buf, size_t count, loff_t *f_pos)
EXPORT_SYMBOL (pciedev_read_exp)
ssize_t pciedev_write_exp (struct file *filp, const char __user *buf, size_t count, loff_t *f_pos)
EXPORT_SYMBOL (pciedev_write_exp)
loff_t pciedev_llseek (struct file *filp, loff_t off, int frm)
int pciedev_check_scratch (struct pciedev_dev *dev, int rmode)
Function Documentation
EXPORT_SYMBOL (pciedev_read_exp)
EXPORT_SYMBOL (pciedev_write_exp)
int pciedev_check_scratch (struct pciedev_dev * dev, int rmode)
References pciedev_dev::dev_mut, pciedev_dev::mem_base0_end, pciedev_dev::mem_base1_end, pciedev_dev::mem_base2_end, pciedev_dev::mem_base3_end, pciedev_dev::mem_base4_end, pciedev_dev::mem_base5_end, pciedev_dev::memmory_base0, pciedev_dev::memmory_base1, pciedev_dev::memmory_base2, pciedev_dev::memmory_base3, pciedev_dev::memmory_base4, pciedev_dev::memmory_base5, RW_D16, RW_D32, RW_D8, pciedev_dev::scratch_bar, and pciedev_dev::scratch_offset.
Referenced by pciedev_read_exp().
loff_t pciedev_llseek (struct file * filp, loff_t off, int frm)
References pciedev_dev::dev_minor, pciedev_dev::dev_num, pciedev_dev::dev_sts, and PCIED_FPOS.
Referenced by upciedev_init_module_exp().
ssize_t pciedev_read_exp (struct file * filp, char __user * buf, size_t count, loff_t * f_pos)
References device_rw::barx_rw, device_rw::data_rw, pciedev_dev::dev_minor, pciedev_dev::dev_mut, pciedev_dev::dev_num, pciedev_dev::dev_sts, pciedev_dev::mem_base0_end, pciedev_dev::mem_base1_end, pciedev_dev::mem_base2_end, pciedev_dev::mem_base3_end, pciedev_dev::mem_base4_end, pciedev_dev::mem_base5_end, pciedev_dev::memmory_base0, pciedev_dev::memmory_base1, pciedev_dev::memmory_base2, pciedev_dev::memmory_base3, pciedev_dev::memmory_base4, pciedev_dev::memmory_base5, device_rw::mode_rw, device_rw::offset_rw, pciedev_dev::parent_dev, PCIED_FPOS, pciedev_dev::pciedev_all_mems, pciedev_check_scratch(), pciedev_cdev::PCIEDEV_DRV_VER_MAJ, pciedev_cdev::PCIEDEV_DRV_VER_MIN, pciedev_dev::pciedev_pci_dev, device_rw::rsrvd_rw, RW_D16, RW_D32, RW_D8, RW_INFO, device_rw::size_rw, and pciedev_dev::slot_num.
ssize_t pciedev_write_exp (struct file * filp, const char __user * buf, size_t count, loff_t * f_pos)
References device_rw::barx_rw, device_rw::data_rw, pciedev_dev::dev_minor, pciedev_dev::dev_mut, pciedev_dev::dev_num, pciedev_dev::dev_sts, DMA_DATA_OFFSET_BYTE, pciedev_dev::mem_base0_end, pciedev_dev::mem_base1_end, pciedev_dev::mem_base2_end, pciedev_dev::mem_base3_end, pciedev_dev::mem_base4_end, pciedev_dev::mem_base5_end, pciedev_dev::memmory_base0, pciedev_dev::memmory_base1, pciedev_dev::memmory_base2, pciedev_dev::memmory_base3, pciedev_dev::memmory_base4, pciedev_dev::memmory_base5, device_rw::mode_rw, device_rw::offset_rw, PCIED_FPOS, device_rw::rsrvd_rw, RW_D16, RW_D32, RW_D8, and device_rw::size_rw.